/*
BASIC SQL

Exercise 4: List the share firm name, share price, share quantity, and 
total value of shares held (this is share quantity multiplies share price). 
If there is a space in your alias, use double quotes around the alias.
*/

SELECT shrfirm, shrprice, shrqty, (shrqty * shrprice) as "Total Value of Shares"
    FROM shares;
    
/*
Ex 5: List full details for all shares with a price less than one dollar
*/

SELECT *
    FROM shares
    WHERE shrprice < 1;

/*
Ex 6: List the share firm name and yield of all shares with a yield exceeding 5
percent (yield is equal to share dividend divided by share price).
*/

SELECT shrfirm, ROUND(shrdiv/shrprice, 3) as Yield
    FROM shares
    WHERE shrdiv/shrprice > 0.05;

/*
Ex 7: Report the total dividend payment of Patagonian Tea (the total dividend
payment is share dividend times share quantity).
*/

SELECT shrdiv * shrqty as Total_Div
    FROM shares
    WHERE shrfirm = 'Patagonian Tea';

/*
Ex 8: Find all shares where the price is less than 20 times the dividend.
*/

SELECT *
    FROM shares
    WHERE shrprice < (20*shrdiv);
    
/*
Ex 9: Find the total value of the shares of Abyssinian Ruby and Sri Lankan Gold.
*/

SELECT shrfirm, (shrqty * shrprice) as "Total Value of Shares"
    FROM shares
    WHERE shrfirm IN ('Abyssinian Ruby', 'Sri Lankan Gold');

/*
Ex 10: Find the yield of all shares except Bolivian Tea and Canadian Sugar.
*/

SELECT shrfirm, ROUND(shrdiv/shrprice, 3) as Yield
    FROM shares
    WHERE shrfirm NOT IN ('Bolivian Tea', 'Canadian Sugar');

/*
Ex 11: List share codes of shares whose PE ratio is between 10 and 20.
*/

SELECT shrcode 
    FROM shares
    WHERE shrpe BETWEEN 10 AND 20; 
    -- BETWEEN IS INCLUSIVE SO THIS INCLUDES 10 AND 20

/*
Ex 12: List share codes with a share name containing 'Gold’.
*/

SELECT shrcode
    FROM shares
    WHERE shrfirm LIKE '%Gold%';

/*
Ex 13: Find share firm names with a share code starting with ‘B’.
*/

SELECT shrfirm
    FROM shares
    WHERE shrcode LIKE 'B%';

/*
Ex 14: List share firm name and value in descending order of value.
*/

SELECT shrfirm, (shrqty * shrprice) as "Total Value"
    FROM shares
    ORDER BY "Total Value" DESC;
    
-- -----------------------------------------------------------------------------

/*
SQL ADDITIONAL BASIC EXERCISES
use album_ddl which has tables: album
*/

/*
1. show all the genres in the database. Remove duplicates.
*/

SELECT DISTINCT genre
    FROM album;

/*
2. show the ID and name of all albums with a sales quantity greater than 200. 
Sort the output by album name in ascending order.
*/

SELECT aid, aname
    FROM album
    WHERE sales_qty > 200
    ORDER BY aname;

/*
3. show the ID and name of all albums with a price between 10 and 15.
*/

SELECT aid, aname 
    FROM album
    WHERE price BETWEEN 10 AND 15;

/*
4. show the name, year, and genre of all albums with pop, country, or Christmas 
music.
*/

SELECT aname, year, genre
    FROM album 
    WHERE LOWER(genre) in ('pop', 'country', 'christmas');

/*
5. show the ID of albums whose name begins with “S” or “R”
*/

SELECT aid
    FROM album
    WHERE aname LIKE 'S%' or aname LIKE 'R%';

/*
6. show the ID and name of all albums whose name does not end with “u” or “e”. 
Sort the output by year and then by album name in descending order
*/

SELECT aid, aname
    FROM album
    WHERE aname NOT LIKE '%u' AND aname NOT LIKE '%e'
    ORDER BY year, aname DESC;

/*
7. show the total revenue generated by all the albums in the database. Revenue 
of each album is price*sales_qty. (suggested answers are on the next page)
*/

SELECT SUM(price * sales_qty) as Total_Revenue
    FROM album;
    
-- -----------------------------------------------------------------------------
/* 
SQL ADVANCED 1

Ex1: List the total number of firms included in the shares table
*/

SELECT COUNT(shrfirm)
    FROM shares;

/*
Ex2: Find the lowest share price
*/

SELECT MIN(shrprice)
    FROM shares;

/*
Ex3: Find the average share PE ratio
*/

SELECT AVG(shrpe)
    FROM shares;

/*
Ex4: Find the highest yield (yield=shrdiv/shrprice)
*/

SELECT ROUND(MAX(shrdiv/shrprice), 2) as Max_Yield
    FROM shares;
    
/*
USING DONOR, GIFT AND YEAR FOR FOLLOWING QUESTIONS

Ex 5: List the total amount of donations each year, sort by year.
*/

SELECT SUM(amount) as total_donations, year
    FROM gift
    GROUP BY year;

/*
Ex 6: Find the number of donors donated each year, and list those years
when at least 10 donors donated.
*/

SELECT COUNT(donorno), year 
    FROM gift
    GROUP BY year
    HAVING COUNT(donorno) >= 10;

/*
Ex7: List the ID and name of donors who did not give in 1995.
*/

SELECT donorno 
    FROM donor
    WHERE donorno NOT IN (
        SELECT donorno
            FROM gift
            WHERE year = 1995
    );

/*
Ex8: List the ID and name of donors whose total donation is at least twice
the average donation amount across all years.
*/

SELECT donorno, dfname, dlname 
    FROM donor
    WHERE donorno IN (
        SELECT donorno
            FROM gift
            GROUP BY donorno
            HAVING SUM(amount) > 2*(
                SELECT AVG(amount)
                    FROM gift
            )
    );


/*
Ex9: In which years did the total donated exceed the highest year goal of all
years?
*/

SELECT year
    FROM gift
    GROUP BY year
    HAVING SUM(amount) > (
        SELECT MAX(yeargoal)
            FROM year
    );

/*
Ex10:List the ID, state, and name of the donor who made the least donation
in 1993.
*/

SELECT donorno, dstate, dlname, dfname  
    FROM donor
    WHERE donorno IN (
        SELECT donorno
            FROM gift
            WHERE amount = (
                SELECT MIN(amount)
                    FROM gift
                    WHERE year = 1993
            ) AND year = 1993
    );

/*
Ex11:Find the ID and name of the donor who made the largest donation in
1992 and the ID and name of the donor who made the smallest donation in
1992.
*/

SELECT donorno, dlname, dfname 
    FROM donor 
    WHERE donorno = (
        SELECT donorno
            FROM gift
            WHERE amount = (
                SELECT MAX(amount)
                    FROM gift
                    WHERE year = 1992
            ) AND year = 1992
    )
UNION
SELECT donorno, dlname, dfname 
    FROM donor 
    WHERE donorno = (
        SELECT donorno
            FROM gift
            WHERE amount = (
                SELECT MIN(amount)
                    FROM gift
                    WHERE year = 1992
            ) AND year = 1992
    );
    
/*
Ex12: show all the attributes in the Donor, Gift, and Year tables
*/

SELECT * 
    FROM donor, gift, year
    WHERE donor.donorno = gift.donorno AND year.year = gift.year;

/*
Ex13: List the total amount given by each person across all years, sort by
donor last name.
*/

SELECT SUM(amount) as "Total Amount", gift.donorno, dlname, dfname
    FROM donor, gift
    WHERE donor.donorno = gift.donorno
    GROUP BY gift.donorno, dlname, dfname
    ORDER BY dlname, dfname;

/*
Ex14: Report the total donations in 1994 by state.
*/

SELECT SUM(amount), dstate
    FROM donor, gift
    WHERE donor.donorno = gift.donorno AND year = 1994
    GROUP BY dstate;

/*
Ex15: List the ID and name of the donors who donated in the years when
the total donated exceeded the goal for the year.
*/

SELECT DISTINCT gift.donorno, dlname, dfname
    FROM donor, gift
    WHERE donor.donorno = gift.donorno AND YEAR IN (
        SELECT year
            FROM gift
            GROUP BY year
            HAVING SUM(amount) > (
                SELECT yeargoal
                    FROM year
                    WHERE year.year = gift.year
            )
    );
    
/*
ADVANCED SQL 2
USING MUSIC DB -- ARTIST, CREATION, PLAYED, TAG, TRACK, USERS
*/
    
/*
Ex16: show the ID and name of tags that have been used in play lists, and
PID of the play lists.
*/

SELECT tag.tagid, tagname, pid
    FROM tag INNER JOIN played
    ON tag.tagid = played.tagid;

/*
Ex17: show the ID and name of all tags, and PID of the play lists that have
used the tags.
*/

SELECT tag.tagid, tagname, pid
    FROM tag LEFT JOIN played
    ON tag.tagid = played.tagid;
    
SELECT userid, fpmanager_id
FROM users
WHERE userid = fpmanager_id;

    







